name: Validar y Ejecutar Notebook

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Ejecutar el Notebook completo (CI)
        run: |
          jupyter nbconvert --to notebook --execute pre_entrega.ipynb --output resultado_ejecucion.ipynb